name: Build WorkFlow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: checkout submodules
        run: git submodule sync --recursive && git submodule update --init --recursive

      - name: Set gradle permissions
        run: sudo chmod +x android-app/gradlew
      - name: Download dependencies
        run: |
          ./gradlew app:dependencies
      - name: Build debug
        run: |
          ./gradlew assembleDebug

      - name: Test debug
        run: |
          ./gradlew testDebugUnitTest